ALTER TABLE "article" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "tag" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "social_post" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "app_user" ALTER COLUMN "id" SET GENERATED BY DEFAULT;
