CREATE TABLE "social_account" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "social_account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"network" text NOT NULL,
	"external_id" text,
	"username" text,
	"display_name" text,
	"biography" text,
	"avatar_url" text,
	"followers" integer,
	"media_count" integer,
	"visible" boolean DEFAULT true NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"posts_on_home" integer DEFAULT 6 NOT NULL,
	"last_sync_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "social_account_network" CHECK ("social_account"."network" in ('instagram', 'linkedin'))
);
--> statement-breakpoint
ALTER TABLE "social_post" ADD COLUMN "account_id" integer;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_social_account_network_external_id" ON "social_account" USING btree ("network","external_id");--> statement-breakpoint
ALTER TABLE "social_post" ADD CONSTRAINT "social_post_account_id_social_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."social_account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- Reprise de l'unique compte d'avant.
--
-- Écrit à la main, et CONDITIONNÉ à l'existence du jeton : sur une base qui
-- n'a jamais connecté Instagram — le cas de toutes les bases de test — ce
-- bloc ne fait rien.
--
-- Ni la ligne `secret` d'origine ni le réglage `instagram_public` ne sont
-- supprimés : l'ancien conteneur tourne encore pendant le déploiement et les
-- lit. Ils deviennent inertes ; une migration ultérieure pourra les retirer.
DO $$
DECLARE
  profil jsonb := (SELECT value FROM setting WHERE key = 'instagram_public');
  technique jsonb := (SELECT value FROM setting WHERE key = 'instagram');
  compte integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM secret WHERE key = 'instagram_access_token') THEN
    RETURN;
  END IF;

  INSERT INTO social_account (
    network, external_id, username, display_name, biography, avatar_url, followers, media_count
  ) VALUES (
    'instagram',
    nullif(technique ->> 'accountId', ''),
    nullif(ltrim(coalesce(profil ->> 'handle', ''), '@'), ''),
    profil ->> 'name',
    profil ->> 'biography',
    profil ->> 'avatar',
    (profil ->> 'followers')::integer,
    (profil ->> 'posts')::integer
  ) RETURNING id INTO compte;

  -- Le jeton devient celui DU compte : une clé par compte.
  INSERT INTO secret (key, ciphertext, updated_at)
  SELECT 'instagram_access_token:' || compte, ciphertext, updated_at
  FROM secret WHERE key = 'instagram_access_token';

  UPDATE social_post SET account_id = compte WHERE network = 'instagram';
END $$;
