# Traefik's DYNAMIC configuration: the development certificates.
#
# Separate from the static configuration because Traefik RE-READS it live,
# where the other is only read at startup. Generated by ./setup, gitignored.
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/local.pem
        keyFile: /certs/local-key.pem
  certificates:
    - certFile: /certs/local.pem
      keyFile: /certs/local-key.pem
